# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f72b71946d01052586ea04a3d61574b8b99a291f36866bcfe9ff2e784c8929d4df3eae05338013ceb2a5272a8c8fdc49ad597e53ebf043fa5ca79aef9c67348

test:
  secret_key_base: 9c81f439fa4e7f88e3187bcfc363a23e05c7f8f253387f3791cffdb283257dc97708c1c1e2395d9ef2ad91b71ba1b37ae47b34d12fb6b5dad448e81357299232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
